x-challenges:
  FLAG:
    name: "codex-multi-04"
    description: "Use the frontend SSH service to reach the backend and retrieve the flag."
    connection-info: "ssh -p {PORT} root@{HOST}"
    port-id: "1705"
    score: 180

services:
  backend:
    image: docker.cs.kau.se/csma/cyber-range/public-challenges/examples/multi-service-backend:25.1
    environment:
      FLAG: "crl{FLAG}"
      BACKENDPASS: "CRL{PASSWORD}"
  frontend:
    image: docker.cs.kau.se/csma/cyber-range/public-challenges/examples/multi-service-frontend:25.1
    environment:
      ROOTPWD: "password"
      BACKENDPASS: "CRL{LINK:backend:BACKENDPASS}"
    ports:
      - "1705:22/tcp"
