x-challenges:
  FLAG:
    name: "gen-01-weak-ssh"
    description: "Log in via SSH with a weak password and locate the flag."
    connection-info: "ssh -p {PORT} root@{HOST}"
    port-id: "1401"
    score: 100

services:
  server:
    image: docker.cs.kau.se/csma/cyber-range/public-challenges/examples/base:25.1
    environment:
      FLAG: "crl{FLAG}"
      ROOTPWD: "password"
    ports:
      - "1401:22/tcp"
