x-challenges:
  FLAGA:
    name: "codex-combined-03-ssh"
    description: "Connect via SSH and find the flag on disk."
    connection-info: "ssh -p {PORT} root@{HOST}"
    port-id: "1703"
    score: 200
  FLAGB:
    name: "codex-combined-03-web"
    description: "Visit the web page and capture the flag."
    connection-info: "http://{HOST}:{PORT}"
    port-id: "1704"
    score: 200

services:
  app:
    image: docker.cs.kau.se/csma/cyber-range/public-challenges/examples/combined:25.1
    environment:
      ROOTPWD: "password"
      FLAGA: "crl{FLAG}"
      FLAGB: "crl{FLAG}"
    ports:
      - "1703:22/tcp"
      - "1704:80/tcp"
